let sb=null, state={user:null, customers:[], reps:[], visits:[], orders:[], collections:[], quotes:[], users:[]};
const DENSITY={HDPE:.95,LDPE:.92,LLDPE:.918,PP:.90,MIX:.93};
function today(){return new Date().toISOString().slice(0,10)}
function month(){return today().slice(0,7)}
function roleText(r){return r==='admin'?'مدير النظام':r==='sales'?'مدير المبيعات':'مندوب مبيعات'}
function id(){return crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random())}
function cfgOK(){return JMS_CONFIG.SUPABASE_URL&&!JMS_CONFIG.SUPABASE_URL.includes('PUT_')}
function initSupabase(){if(cfgOK()) sb=supabase.createClient(JMS_CONFIG.SUPABASE_URL,JMS_CONFIG.SUPABASE_ANON_KEY)}
function useLocal(){return !sb}
function localDB(){return JSON.parse(localStorage.jms_real_db||'{}')}
function saveLocal(db){localStorage.jms_real_db=JSON.stringify(db)}
function seedLocal(){let db=localDB();if(!db.users){db={users:[{id:'u1',name:'مدير النظام',email:'admin@jms.local',password:'123456',role:'admin',active:true},{id:'r1',name:'ياسر الحسني',email:'rep@jms.local',password:'123456',role:'rep',active:true}],customers:[],visits:[],orders:[],collections:[],quotes:[]};saveLocal(db)}return db}
async function login(){initSupabase();const email=loginEmail.value.trim(),pass=loginPassword.value.trim();if(useLocal()){let db=seedLocal();let u=db.users.find(x=>x.email===email&&x.password===pass&&x.active);if(!u)return alert('بيانات الدخول غير صحيحة');state.user=u;await loadAll();showApp();return}let {data,error}=await sb.from('users').select('*').eq('email',email).eq('password',pass).eq('active',true).maybeSingle();if(error||!data)return alert('بيانات الدخول غير صحيحة');state.user=data;await loadAll();showApp()}
function logout(){location.reload()}
function showApp(){login.classList.add('hidden');app.classList.remove('hidden');currentUserName.textContent=state.user.name;currentUserRole.textContent=roleText(state.user.role);document.querySelectorAll('.admin-only').forEach(x=>x.style.display=state.user.role==='admin'?'block':'none');if(state.user.role==='rep'){document.querySelectorAll('.nav').forEach(b=>{if(!['customers','visits','orders','quotes','collections'].includes(b.dataset.page))b.style.display='none'})}renderAll()}
async function loadAll(){if(useLocal()){let db=seedLocal();state.users=db.users;state.reps=db.users.filter(u=>u.role==='rep');state.customers=db.customers||[];state.visits=db.visits||[];state.orders=db.orders||[];state.collections=db.collections||[];state.quotes=db.quotes||[];return}let [u,c,v,o,col]=await Promise.all([sb.from('users').select('*').order('created_at',{ascending:false}),sb.from('customers').select('*').order('created_at',{ascending:false}),sb.from('visits').select('*').order('visit_date',{ascending:false}),sb.from('orders').select('*').order('order_date',{ascending:false}),sb.from('collections').select('*').order('collection_date',{ascending:false}),sb.from('quotes').select('*').order('quote_date',{ascending:false})]);state.users=u.data||[];state.reps=state.users.filter(x=>x.role==='rep');state.customers=c.data||[];state.visits=v.data||[];state.orders=o.data||[];state.collections=col.data||[];state.quotes=arguments[0]||state.quotes}
async function insert(table,row){if(useLocal()){let db=seedLocal();db[table]=db[table]||[];db[table].unshift(row);saveLocal(db);await loadAll();return row}let {data,error}=await sb.from(table).insert(row).select().single();if(error){alert(error.message);throw error}await loadAll();return data}
async function updateRow(table,rowId,patch){if(useLocal()){let db=seedLocal();let r=(db[table]||[]).find(x=>x.id===rowId);Object.assign(r,patch);saveLocal(db);await loadAll();return}await sb.from(table).update(patch).eq('id',rowId);await loadAll()}
function allowedCustomers(){return state.user.role==='rep'?state.customers.filter(c=>c.rep_id===state.user.id):state.customers}
function repName(id){return (state.users.find(u=>u.id===id)||{}).name||'-'}
function customerName(id){return (state.customers.find(c=>c.id===id)||{}).name||'-'}
function lastVisit(cid){let v=state.visits.filter(x=>x.customer_id===cid).sort((a,b)=>String(b.visit_date).localeCompare(String(a.visit_date)))[0];return v?v.visit_date:null}
function daysFrom(d){if(!d)return null;return Math.floor((new Date(today())-new Date(d))/86400000)}
function statusBadge(c){let d=daysFrom(lastVisit(c.id));if(d===null)return ['لم تتم زيارته','badge'];if(d>=30)return ['متأخر '+d+' يوم','badge red'];return ['آخر زيارة منذ '+d+' يوم','badge green']}
function renderAll(){renderDashboard();renderCustomers();renderVisits();renderOrders();renderQuotes();renderCollections();renderUsers()}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav,.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.page).classList.add('active');renderAll()})
function renderDashboard(){let cs=allowedCustomers(),vs=state.visits.filter(v=>String(v.visit_date||'').startsWith(month())),os=state.orders.filter(o=>String(o.order_date||'').startsWith(month())),cols=state.collections.filter(c=>String(c.collection_date||'').startsWith(month()));statCustomers.textContent=cs.length;statVisits.textContent=vs.length;statOrders.textContent=os.length;statSales.textContent=os.reduce((s,o)=>s+Number(o.total_amount||0),0).toLocaleString('ar-SA');statCollections.textContent=cols.reduce((s,c)=>s+Number(c.amount||0),0).toLocaleString('ar-SA');let late=cs.filter(c=>{let d=daysFrom(lastVisit(c.id));return d===null||d>=30});statLate.textContent=late.length;lateCustomers.innerHTML=late.slice(0,8).map(c=>`<div class="alert-line"><b>${c.name}</b><br>${daysFrom(lastVisit(c.id))===null?'لم تتم زيارته':daysFrom(lastVisit(c.id))+' يوم بدون زيارة'}</div>`).join('')||'لا توجد تنبيهات';recentVisitNotes.innerHTML=state.visits.slice(0,8).map(v=>`<div class="note-line"><b>${customerName(v.customer_id)}</b><br>${v.note||'-'}<br><small>${repName(v.rep_id)} - ${v.visit_date}</small></div>`).join('')||'لا توجد ملاحظات'}
function renderCustomers(){let q=(customerSearch?.value||'').trim();let list=allowedCustomers().filter(c=>!q||`${c.name} ${c.phone} ${c.city}`.includes(q));customersList.innerHTML=list.map(c=>{let [txt,cls]=statusBadge(c);return `<div class="card"><h3>${c.name}</h3><span class="${cls}">${txt}</span><p>الجوال: ${c.phone||'-'}<br>المدينة: ${c.city||'-'}<br>المندوب: ${repName(c.rep_id)}<br>المديونية: ${Number(c.debt_balance||0).toLocaleString('ar-SA')} ريال</p><div class="actions"><button class="green" onclick="openVisitForm('${c.id}')">تقرير زيارة</button><button class="blue" onclick="openOrderForm('${c.id}')">طلب جديد</button><button class="orange" onclick="openCollectionForm('${c.id}')">تحصيل</button></div></div>`}).join('')||'<div class="panel">لا يوجد عملاء</div>'}
function renderVisits(){visitsList.innerHTML=state.visits.map(v=>`<div class="card"><h3>${customerName(v.customer_id)}</h3><p>المندوب: ${repName(v.rep_id)}<br>التاريخ: ${v.visit_date}<br>النوع: ${v.visit_type||'-'}<br>الملاحظة: ${v.note||'-'}<br>موعد المتابعة: ${v.followup_date||'-'}</p></div>`).join('')||'<div class="panel">لا توجد زيارات</div>'}
function renderOrders(){ordersList.innerHTML=state.orders.map(o=>`<div class="card"><h3>${customerName(o.customer_id)}</h3><p>المنتج: ${o.product}<br>المقاس: ${o.width} × ${o.length}<br>السماكة: ${o.thickness}<br>الخامة: ${o.material}<br>الكمية: ${o.total_kg} كجم<br>الإجمالي: ${Number(o.total_amount||0).toLocaleString('ar-SA')} ريال</p></div>`).join('')||'<div class="panel">لا توجد طلبات</div>'}
function renderCollections(){collectionsList.innerHTML=state.collections.map(c=>`<div class="card"><h3>${customerName(c.customer_id)}</h3><p>المبلغ: ${Number(c.amount||0).toLocaleString('ar-SA')} ريال<br>التاريخ: ${c.collection_date}<br>الطريقة: ${c.method||'-'}<br>المندوب: ${repName(c.rep_id)}</p></div>`).join('')||'<div class="panel">لا توجد تحصيلات</div>'}
function renderUsers(){if(!usersList)return;usersList.innerHTML=state.users.map(u=>`<div class="card"><h3>${u.name}</h3><p>${u.email}<br>${roleText(u.role)}<br>${u.active?'نشط':'موقوف'}</p></div>`).join('')}
function closeModal(){modal.classList.add('hidden');modalBody.innerHTML=''}
function repOptions(selected=''){return state.reps.map(r=>`<option value="${r.id}" ${selected===r.id?'selected':''}>${r.name}</option>`).join('')}
function customerOptions(selected=''){return allowedCustomers().map(c=>`<option value="${c.id}" ${selected===c.id?'selected':''}>${c.name}</option>`).join('')}
function openCustomerForm(){modalBody.innerHTML=`<h2>إضافة عميل</h2><div class="form-grid"><label>اسم العميل<input id="cName"></label><label>الجوال<input id="cPhone"></label><label>المدينة<input id="cCity" value="جدة"></label><label>المندوب<select id="cRep">${repOptions()}</select></label><label>المديونية<input id="cDebt" type="number" value="0"></label><label>الموقع<input id="cLocation"></label></div><br><button class="primary" onclick="saveCustomer()">حفظ العميل</button>`;modal.classList.remove('hidden')}
async function saveCustomer(){await insert('customers',{id:id(),name:cName.value,phone:cPhone.value,city:cCity.value,rep_id:cRep.value,debt_balance:Number(cDebt.value||0),location:cLocation.value,created_at:new Date().toISOString()});closeModal();renderAll()}
function openVisitForm(cid=''){modalBody.innerHTML=`<h2>تقرير زيارة</h2><div class="form-grid"><label>العميل<select id="vCustomer">${customerOptions(cid)}</select></label><label>التاريخ<input id="vDate" type="date" value="${today()}"></label><label>نوع الزيارة<select id="vType"><option>متابعة</option><option>طلب جديد</option><option>تحصيل</option><option>شكوى</option><option>طلب موعد</option></select></label><label>موعد المتابعة<input id="vFollow" type="date"></label></div><br><label>ملاحظات الزيارة<textarea id="vNote" rows="5"></textarea></label><br><button class="primary" onclick="saveVisit()">حفظ تقرير الزيارة</button>`;modal.classList.remove('hidden')}
async function saveVisit(){let c=state.customers.find(x=>x.id===vCustomer.value);await insert('visits',{id:id(),customer_id:vCustomer.value,rep_id:c.rep_id||state.user.id,visit_date:vDate.value,visit_type:vType.value,note:vNote.value,followup_date:vFollow.value,created_at:new Date().toISOString()});closeModal();renderAll()}
function calcOrder(){let w=Number(oWidth?.value||0)/100,l=Number(oLength?.value||0)/100,t=Number(oThick?.value||0),den=DENSITY[oMat?.value]||.93;let g=w*l*t*den;oPiece.value=g?g.toFixed(2):'';let kg=Number(oKg.value||0);oPieces.value=g?Math.floor(kg/(g/1000)):'';oTotal.value=(kg*Number(oPrice.value||0)).toFixed(2)}
function openOrderForm(cid=''){modalBody.innerHTML=`<h2>طلب تصنيع</h2><div class="form-grid four"><label>العميل<select id="oCustomer">${customerOptions(cid)}</select></label><label>المنتج<input id="oProduct" value="أكياس رول"></label><label>العرض سم<input id="oWidth" type="number" oninput="calcOrder()"></label><label>الطول سم<input id="oLength" type="number" oninput="calcOrder()"></label><label>السماكة ميكرون<input id="oThick" type="number" oninput="calcOrder()"></label><label>الخامة<select id="oMat" onchange="calcOrder()"><option>HDPE</option><option>LDPE</option><option>LLDPE</option><option>PP</option></select></label><label>الكمية كجم<input id="oKg" type="number" oninput="calcOrder()"></label><label>سعر الكيلو<input id="oPrice" type="number" oninput="calcOrder()"></label><label>وزن الحبة جرام<input id="oPiece" readonly></label><label>عدد الحبات<input id="oPieces" readonly></label><label>الإجمالي<input id="oTotal" readonly></label></div><br><button class="primary" onclick="saveOrder()">حفظ الطلب</button>`;modal.classList.remove('hidden')}
async function saveOrder(){let c=state.customers.find(x=>x.id===oCustomer.value);await insert('orders',{id:id(),customer_id:oCustomer.value,rep_id:c.rep_id||state.user.id,order_date:today(),product:oProduct.value,width:oWidth.value,length:oLength.value,thickness:oThick.value,material:oMat.value,total_kg:Number(oKg.value||0),piece_weight:Number(oPiece.value||0),pieces:Number(oPieces.value||0),price_kg:Number(oPrice.value||0),total_amount:Number(oTotal.value||0),status:'جديد',created_at:new Date().toISOString()});closeModal();renderAll()}
function openCollectionForm(cid=''){modalBody.innerHTML=`<h2>تسجيل تحصيل</h2><div class="form-grid"><label>العميل<select id="colCustomer">${customerOptions(cid)}</select></label><label>المبلغ<input id="colAmount" type="number"></label><label>التاريخ<input id="colDate" type="date" value="${today()}"></label><label>طريقة التحصيل<select id="colMethod"><option>نقدي</option><option>تحويل</option><option>شبكة</option><option>شيك</option></select></label></div><br><button class="primary" onclick="saveCollection()">حفظ التحصيل</button>`;modal.classList.remove('hidden')}
async function saveCollection(){let c=state.customers.find(x=>x.id===colCustomer.value);await insert('collections',{id:id(),customer_id:colCustomer.value,rep_id:c.rep_id||state.user.id,amount:Number(colAmount.value||0),collection_date:colDate.value,method:colMethod.value,created_at:new Date().toISOString()});await updateRow('customers',colCustomer.value,{debt_balance:Number(c.debt_balance||0)-Number(colAmount.value||0)});closeModal();renderAll()}
function openUserForm(){modalBody.innerHTML=`<h2>إضافة مستخدم</h2><div class="form-grid"><label>الاسم<input id="uName"></label><label>الإيميل<input id="uEmail"></label><label>كلمة المرور<input id="uPass" value="123456"></label><label>الصلاحية<select id="uRole"><option value="rep">مندوب</option><option value="sales">مدير مبيعات</option><option value="admin">مدير نظام</option></select></label></div><br><button class="primary" onclick="saveUser()">حفظ المستخدم</button>`;modal.classList.remove('hidden')}
async function saveUser(){await insert('users',{id:id(),name:uName.value,email:uEmail.value,password:uPass.value,role:uRole.value,active:true,created_at:new Date().toISOString()});closeModal();renderAll()}
seedLocal();


function quoteStatusText(s){return s==='pending'?'بانتظار اعتماد المدير':s==='approved'?'معتمد':s==='sent'?'مرسل للعميل':s==='accepted'?'مقبول من العميل':s==='cancelled'?'ملغي - العميل لم يوافق':s==='rejected'?'مرفوض من المدير':'-'}
function allowedQuotes(){return state.user.role==='rep'?state.quotes.filter(q=>q.rep_id===state.user.id):state.quotes}
function nextQuoteNo(){return 'Q-'+String((state.quotes.length||0)+1).padStart(5,'0')}
function renderQuotes(){
  if(!window.quotesList)return;
  let st=quoteStatusFilter?.value||'all';
  let list=allowedQuotes().filter(q=>st==='all'||q.status===st);
  quotesList.innerHTML=list.map(q=>`<div class="card">
    <h3>عرض رقم ${q.quote_no}</h3>
    <span class="quote-status ${q.status}">${quoteStatusText(q.status)}</span>
    <p>العميل: ${customerName(q.customer_id)}<br>المندوب: ${repName(q.rep_id)}<br>التاريخ: ${q.quote_date}<br>المنتج: ${q.product||'-'}<br>المقاس: ${q.width||'-'} × ${q.length||'-'}<br>السماكة: ${q.thickness||'-'}<br>الخامة: ${q.material||'-'}<br>الكمية: ${q.total_kg||0} كجم<br>الإجمالي: ${Number(q.total_amount||0).toLocaleString('ar-SA')} ريال<br>${q.cancel_reason?'سبب الإلغاء: '+q.cancel_reason:''}</p>
    <div class="actions">
      ${(state.user.role==='admin'||state.user.role==='sales')&&q.status==='pending'?`<button class="green" onclick="approveQuote('${q.id}')">اعتماد</button><button onclick="rejectQuote('${q.id}')">رفض</button>`:''}
      ${q.status==='approved'?`<button class="blue" onclick="sendQuoteToCustomer('${q.id}')">تم الإرسال للعميل</button>`:''}
      ${q.status==='sent'?`<button class="green" onclick="acceptQuote('${q.id}')">العميل وافق</button><button class="orange" onclick="cancelQuote('${q.id}')">إلغاء - العميل لم يوافق</button>`:''}
      ${q.status==='accepted'?`<button class="orange" onclick="convertQuoteToOrderReal('${q.id}')">تحويل لطلب</button>`:''}
    </div>
  </div>`).join('')||'<div class="panel">لا توجد عروض أسعار</div>';
}
function openQuoteForm(cid=''){
  modalBody.innerHTML=`<h2>عرض سعر جديد</h2><div class="form-grid four">
  <label>العميل<select id="qCustomer">${customerOptions(cid)}</select></label>
  <label>تاريخ العرض<input id="qDate" type="date" value="${today()}"></label>
  <label>صالح حتى<input id="qValid" type="date"></label>
  <label>المنتج<input id="qProduct" value="أكياس رول"></label>
  <label>العرض سم<input id="qWidth" type="number" oninput="calcQuoteReal()"></label>
  <label>الطول سم<input id="qLength" type="number" oninput="calcQuoteReal()"></label>
  <label>السماكة ميكرون<input id="qThick" type="number" oninput="calcQuoteReal()"></label>
  <label>الخامة<select id="qMat" onchange="calcQuoteReal()"><option>HDPE</option><option>LDPE</option><option>LLDPE</option><option>PP</option></select></label>
  <label>اللون<input id="qColor"></label>
  <label>الكمية كجم<input id="qKg" type="number" oninput="calcQuoteReal()"></label>
  <label>سعر الكيلو<input id="qPrice" type="number" oninput="calcQuoteReal()"></label>
  <label>وزن الحبة جرام<input id="qPiece" readonly></label>
  <label>عدد الحبات<input id="qPieces" readonly></label>
  <label>الإجمالي<input id="qTotal" readonly></label>
  </div><br><button class="primary" onclick="saveQuoteReal()">حفظ وإرساله للاعتماد</button>`;
  modal.classList.remove('hidden')
}
function calcQuoteReal(){let w=Number(qWidth?.value||0)/100,l=Number(qLength?.value||0)/100,t=Number(qThick?.value||0),den=DENSITY[qMat?.value]||.93;let g=w*l*t*den;qPiece.value=g?g.toFixed(2):'';let kg=Number(qKg.value||0);qPieces.value=g?Math.floor(kg/(g/1000)):'';qTotal.value=(kg*Number(qPrice.value||0)).toFixed(2)}
async function saveQuoteReal(){let c=state.customers.find(x=>x.id===qCustomer.value);await insert('quotes',{id:id(),quote_no:nextQuoteNo(),customer_id:qCustomer.value,rep_id:c.rep_id||state.user.id,quote_date:qDate.value,valid_until:qValid.value,product:qProduct.value,width:Number(qWidth.value||0),length:Number(qLength.value||0),thickness:Number(qThick.value||0),material:qMat.value,color:qColor.value,total_kg:Number(qKg.value||0),piece_weight:Number(qPiece.value||0),pieces:Number(qPieces.value||0),price_kg:Number(qPrice.value||0),total_amount:Number(qTotal.value||0),status:'pending',created_at:new Date().toISOString()});closeModal();renderAll()}
async function approveQuote(qid){await updateRow('quotes',qid,{status:'approved',approved_by:state.user.id,approved_at:new Date().toISOString()});renderAll()}
async function rejectQuote(qid){let reason=prompt('سبب رفض المدير');await updateRow('quotes',qid,{status:'rejected',manager_note:reason||''});renderAll()}
async function sendQuoteToCustomer(qid){await updateRow('quotes',qid,{status:'sent',sent_at:new Date().toISOString()});renderAll()}
async function acceptQuote(qid){await updateRow('quotes',qid,{status:'accepted',accepted_at:new Date().toISOString()});renderAll()}
async function cancelQuote(qid){let reason=prompt('اكتب سبب إلغاء العرض لأن العميل لم يوافق');if(!reason)return;await updateRow('quotes',qid,{status:'cancelled',cancel_reason:reason,cancelled_at:new Date().toISOString()});renderAll()}
async function convertQuoteToOrderReal(qid){let q=state.quotes.find(x=>x.id===qid);if(!q)return;await insert('orders',{id:id(),customer_id:q.customer_id,rep_id:q.rep_id,order_date:today(),product:q.product,width:q.width,length:q.length,thickness:q.thickness,material:q.material,total_kg:q.total_kg,piece_weight:q.piece_weight,pieces:q.pieces,price_kg:q.price_kg,total_amount:q.total_amount,status:'جديد',created_at:new Date().toISOString()});alert('تم تحويل عرض السعر إلى طلب تصنيع');renderAll()}
