const cfg=window.JMS_CONFIG||{};const supabase=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY);
const todayISO=()=>new Date().toISOString().slice(0,10);const daysBetween=d=>{if(!d)return 9999;return Math.floor((new Date(todayISO()+'T00:00:00')-new Date(d+'T00:00:00'))/86400000)};let db={reps:[],customers:[],visits:[],orders:[]};let currentUser=JSON.parse(sessionStorage.getItem('jms_current_user')||'null');
function showApp(){loginView.classList.add('hidden');appView.classList.remove('hidden');currentUserName.textContent=currentUser?.name||'مدير النظام';refreshAll()}function showLogin(){appView.classList.add('hidden');loginView.classList.remove('hidden')}
loginForm.onsubmit=e=>{e.preventDefault();if(loginEmail.value.trim()==='admin@jms.local'&&loginPassword.value==='123456'){currentUser={name:'مدير النظام',email:'admin@jms.local'};sessionStorage.setItem('jms_current_user',JSON.stringify(currentUser));showApp()}else alert('بيانات الدخول التجريبية غير صحيحة')};function logout(){sessionStorage.removeItem('jms_current_user');currentUser=null;showLogin()}if(currentUser)showApp();else showLogin();
function goTab(tab){document.querySelector(`[data-tab="${tab}"]`).click()}function repNameFn(id){return db.reps.find(r=>r.id===id)?.name||'-'}function customerNameFn(id){return db.customers.find(c=>c.id===id)?.name||'-'}function lastVisit(id){return db.visits.filter(v=>v.customer_id===id).sort((a,b)=>String(b.visit_date).localeCompare(String(a.visit_date)))[0]?.visit_date||''}function status(c){let d=daysBetween(lastVisit(c.id));return d>=30?{t:'متأخر',c:'late',d}:d>=20?{t:'قريب',c:'warn',d}:{t:'منتظم',c:'ok',d}}function money(n){return Number(n||0).toLocaleString('ar-SA')}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-item,.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.tab).classList.add('active');pageTitle.textContent=b.textContent});
async function refreshAll(){try{if(typeof cloudStatus!=='undefined')cloudStatus.innerHTML='جاري الاتصال بقاعدة البيانات...';const [reps,customers,visits,orders]=await Promise.all([supabase.from('reps').select('*').order('created_at',{ascending:false}),supabase.from('customers').select('*').order('created_at',{ascending:false}),supabase.from('visits').select('*').order('visit_date',{ascending:false}),supabase.from('orders').select('*').order('order_date',{ascending:false})]);for(const r of [reps,customers,visits,orders])if(r.error)throw r.error;db.reps=reps.data||[];db.customers=customers.data||[];db.visits=visits.data||[];db.orders=orders.data||[];if(typeof cloudStatus!=='undefined')cloudStatus.innerHTML='✅ الاتصال بالسحابة يعمل بنجاح';render()}catch(err){console.error(err);if(typeof cloudStatus!=='undefined')cloudStatus.innerHTML='❌ خطأ: شغل ملف supabase_schema.sql في Supabase أولاً.<br><br>'+err.message;alert('خطأ في الاتصال بالسحابة: '+err.message)}}
function renderSelects(){let reps='<option value="">اختر المندوب</option>'+db.reps.filter(r=>r.status!=='موقوف').map(r=>`<option value="${r.id}">${r.name}</option>`).join('');let customers='<option value="">اختر العميل</option>'+db.customers.map(c=>`<option value="${c.id}">${c.name}</option>`).join('');customerRep.innerHTML=reps;visitRep.innerHTML=reps;orderRep.innerHTML=reps;visitCustomer.innerHTML=customers;orderCustomer.innerHTML=customers}
function renderStats(){totalCustomers.textContent=db.customers.length;lateCustomers.textContent=db.customers.filter(c=>status(c).d>=30).length;todayVisits.textContent=db.visits.filter(v=>v.visit_date===todayISO()).length;totalOrders.textContent=db.orders.length;salesTotal.textContent=money(db.orders.reduce((s,o)=>s+Number(o.amount||0),0))}
function renderCustomers(){let q=(customerSearch?.value||'').trim();let list=db.customers.filter(c=>!q||String(c.name||'').includes(q)||String(c.phone||'').includes(q)||String(c.city||'').includes(q));let rows=list.map(c=>{let s=status(c),maps=c.location?`<a target="_blank" href="${c.location}">الموقع</a>`:'-';return `<tr><td>${c.name}</td><td>${c.phone||'-'}</td><td>${c.city||'-'}</td><td>${c.activity||'-'}</td><td>${repNameFn(c.rep_id)}</td><td>${lastVisit(c.id)||'لم يزر'}</td><td><span class="badge ${s.c}">${s.t}</span></td><td>${maps}</td></tr>`}).join('');customersList.innerHTML=rows?`<table><thead><tr><th>العميل</th><th>الجوال</th><th>المدينة</th><th>النشاط</th><th>المندوب</th><th>آخر زيارة</th><th>الحالة</th><th>الخريطة</th></tr></thead><tbody>${rows}</tbody></table>`:'لا يوجد عملاء'}
function renderReps(){let rows=db.reps.map(r=>`<tr><td>${r.name}</td><td>${r.phone||'-'}</td><td>${r.email||'-'}</td><td>${r.status}</td><td>${db.customers.filter(c=>c.rep_id===r.id).length}</td><td>${db.visits.filter(v=>v.rep_id===r.id).length}</td></tr>`).join('');repsList.innerHTML=rows?`<table><thead><tr><th>المندوب</th><th>الجوال</th><th>الإيميل</th><th>الحالة</th><th>عملاء</th><th>زيارات</th></tr></thead><tbody>${rows}</tbody></table>`:'لا يوجد مناديب'}
function renderVisits(){let rows=db.visits.map(v=>`<tr><td>${v.visit_date}</td><td>${customerNameFn(v.customer_id)}</td><td>${repNameFn(v.rep_id)}</td><td>${v.status}</td><td>${v.location||'-'}</td><td>${v.notes||'-'}</td></tr>`).join('');visitsList.innerHTML=rows?`<table><thead><tr><th>التاريخ</th><th>العميل</th><th>المندوب</th><th>الحالة</th><th>الموقع</th><th>ملاحظات</th></tr></thead><tbody>${rows}</tbody></table>`:'لا توجد زيارات';let todayRows=db.visits.filter(v=>v.visit_date===todayISO()).map(v=>`<tr><td>${customerNameFn(v.customer_id)}</td><td>${repNameFn(v.rep_id)}</td><td>${v.status}</td><td>${v.notes||'-'}</td></tr>`).join('');todayVisitsTable.innerHTML=todayRows?`<table><thead><tr><th>العميل</th><th>المندوب</th><th>الحالة</th><th>ملاحظات</th></tr></thead><tbody>${todayRows}</tbody></table>`:'لا توجد زيارات اليوم'}
function orderBadge(s){return s==='تم التسليم'?'done':s==='ملغي'?'cancel':'new'}function renderOrders(){let rows=db.orders.map(o=>`<tr><td>${o.order_date}</td><td>${customerNameFn(o.customer_id)}</td><td>${repNameFn(o.rep_id)}</td><td>${o.product||'-'}</td><td>${o.quantity||'-'}</td><td>${money(o.amount)}</td><td><span class="badge ${orderBadge(o.status)}">${o.status}</span></td></tr>`).join('');ordersList.innerHTML=rows?`<table><thead><tr><th>التاريخ</th><th>العميل</th><th>المندوب</th><th>الصنف</th><th>الكمية</th><th>القيمة</th><th>الحالة</th></tr></thead><tbody>${rows}</tbody></table>`:'لا توجد طلبات';latestOrders.innerHTML=rows?`<table><thead><tr><th>التاريخ</th><th>العميل</th><th>الصنف</th><th>القيمة</th><th>الحالة</th></tr></thead><tbody>${db.orders.slice(0,5).map(o=>`<tr><td>${o.order_date}</td><td>${customerNameFn(o.customer_id)}</td><td>${o.product||'-'}</td><td>${money(o.amount)}</td><td>${o.status}</td></tr>`).join('')}</tbody></table>`:'لا توجد طلبات'}
function renderAlerts(){let late=db.customers.filter(c=>status(c).d>=30);let html=late.map(c=>`<div class="list-item"><strong>${c.name}</strong><br>متأخر ${status(c).d} يوم — المندوب: ${repNameFn(c.rep_id)}</div>`).join('');quickAlerts.innerHTML=html||'<div class="list-item">لا يوجد عملاء متأخرين حالياً</div>';alertsList.innerHTML=html||'<div class="list-item">لا توجد تنبيهات</div>'}
function renderTopReps(){let ranked=db.reps.map(r=>({name:r.name,count:db.visits.filter(v=>v.rep_id===r.id).length})).sort((a,b)=>b.count-a.count).slice(0,5);topReps.innerHTML=ranked.map((r,i)=>`<div class="rank-item"><b>${i+1}. ${r.name}</b><span>${r.count} زيارة</span></div>`).join('')||'لا يوجد بيانات'}function render(){renderSelects();renderStats();renderCustomers();renderReps();renderVisits();renderOrders();renderAlerts();renderTopReps()}
repForm.onsubmit=async e=>{e.preventDefault();const {error}=await supabase.from('reps').insert({name:repName.value.trim(),phone:repPhone.value.trim(),email:repEmail.value.trim(),status:repStatus.value});if(error)return alert(error.message);e.target.reset();refreshAll()}
customerForm.onsubmit=async e=>{e.preventDefault();const {error}=await supabase.from('customers').insert({name:customerName.value.trim(),phone:customerPhone.value.trim(),city:customerCity.value.trim(),activity:customerActivity.value.trim(),location:customerLocation.value.trim(),rep_id:customerRep.value||null,notes:customerNotes.value.trim()});if(error)return alert(error.message);e.target.reset();refreshAll()}
visitDate.value=todayISO();visitForm.onsubmit=async e=>{e.preventDefault();const {error}=await supabase.from('visits').insert({customer_id:visitCustomer.value,rep_id:visitRep.value,visit_date:visitDate.value,status:visitStatus.value,location:visitLocation.value.trim(),notes:visitNotes.value.trim()});if(error)return alert(error.message);e.target.reset();visitDate.value=todayISO();refreshAll()}
orderDate.value=todayISO();orderForm.onsubmit=async e=>{e.preventDefault();const {error}=await supabase.from('orders').insert({customer_id:orderCustomer.value,rep_id:orderRep.value,order_date:orderDate.value,product:orderProduct.value.trim(),quantity:orderQuantity.value||null,amount:orderAmount.value||0,status:orderStatus.value});if(error)return alert(error.message);e.target.reset();orderDate.value=todayISO();refreshAll()}
function downloadCSV(lines,name){let csv=lines.map(r=>r.map(x=>`"${String(x??'').replaceAll('"','""')}"`).join(',')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download=name;a.click()}function exportCustomersCSV(){let lines=[['العميل','الجوال','المدينة','النشاط','المندوب','آخر زيارة','الحالة','أيام التأخير']];db.customers.forEach(c=>{let s=status(c);lines.push([c.name,c.phone,c.city,c.activity,repNameFn(c.rep_id),lastVisit(c.id)||'لم يزر',s.t,s.d])});downloadCSV(lines,'JMS_customers_cloud.csv')}function requestNotifications(){if(!('Notification'in window))return alert('المتصفح لا يدعم الإشعارات');Notification.requestPermission().then(p=>{if(p==='granted')new Notification('JMS CRM',{body:'تم تفعيل الإشعارات'})})}
