window.JMS_CONFIG = {
  SUPABASE_URL: "PUT_YOUR_SUPABASE_URL_HERE",
  SUPABASE_ANON_KEY: "PUT_YOUR_SUPABASE_ANON_KEY_HERE",
  COMPANY_NAME_AR: "شركة جدة النموذجية للصناعة",
  COMPANY_NAME_EN: "Jeddah Model Industrial Co. Ltd",
  VAT_RATE: 0.15
};
