import test from 'node:test';
import assert from 'node:assert/strict';
import { executePlan, normalizePlan, fallbackPlan, resolveEntity, scopeData, number, saudiDate } from '../lib/ai-engine.js';
const admin={id:'admin',role:'admin'},rep={id:'osman',role:'rep'};
const fixture=()=>({
 reps:[{id:'osman',name:'عثمان أحمد'},{id:'wesam',name:'وسام علي'}],
 customers:[{id:'a',name:'زهرة الروضة',rep_id:'osman',debt_balance:1000.10,due_amount:200},{id:'b',name:'النواة الذهبية',rep_id:'osman',debt_balance:2000.20,aging_60:2000.20},{id:'c',name:'عميل وسام',rep_id:'wesam',debt_balance:9000},{id:'d',name:'عميل دائن',rep_id:'osman',debt_balance:-500},{id:'e',name:'بلا مندوب',rep_id:'',debt_balance:100}],
 collections:[{id:'p1',customer_id:'a',rep_id:'osman',date:'2026-08-15',amount:500},{id:'p2',customer_id:'a',rep_id:'osman',date:'2026-09-13',amount:800}],
 visits:[],orders:[],quotes:[{id:'q1',quote_no:'Q-100',customer_id:'a',rep_id:'osman',date:'2026-09-13',status:'customer_approved',product:'أكياس بلاستيك',material:'LDPE',width:32,length:40,thickness:70,total_kg:500,price_kg:8,print_colors:2,public_token:'must-not-copy',customer_signature:'must-not-copy'}]
});
test('named representative total excludes other reps and separates credits',()=>{const r=executePlan({action:'debts',rep:'عثمان'},fixture(),admin);assert.equal(r.metrics.total,3000.30);assert.equal(r.metrics.count,2);assert.equal(r.metrics.creditBalance,500);assert.ok(!r.answer.includes('عميل وسام'));});
test('ascending and descending results use numeric sort',()=>{const a=executePlan({action:'debts',rep:'عثمان',sort:'asc'},fixture(),admin);const b=executePlan({action:'debts',rep:'عثمان',sort:'desc'},fixture(),admin);assert.equal(a.sources[0].id,'a');assert.equal(b.sources[0].id,'b');});
test('all 1250 customers contribute to totals while display is limited',()=>{const d=fixture();d.customers=Array.from({length:1250},(_,i)=>({id:String(i),name:'عميل '+i,rep_id:'osman',debt_balance:1000}));const r=executePlan({action:'debts',limit:5},d,admin);assert.equal(r.metrics.total,1250000);assert.equal(r.metrics.count,1250);assert.equal(r.sources.length,5);});
test('due figures do not use aging buckets as due dates',()=>{const r=executePlan({action:'debts',rep:'عثمان',dueOnly:true},fixture(),admin);assert.equal(r.metrics.total,200);assert.equal(r.metrics.unknown,1);assert.ok(r.answer.includes('البيانات المتوفرة فقط'));});
test('missing amount is not a zero balance',()=>{const d=fixture();d.customers.push({id:'missing',name:'ناقص',rep_id:'osman'});assert.equal(executePlan({action:'debts',rep:'عثمان'},d,admin).metrics.unknown,1);});
test('rep cannot request another representative by name',()=>{const r=executePlan({action:'debts',rep:'وسام'},fixture(),rep);assert.equal(r.mode,'clarification');assert.ok(!r.answer.includes('9,000'));});
test('scoping applies before resolving a customer or returning sources',()=>{const r=executePlan({action:'customer_summary',customer:'عميل وسام'},fixture(),rep);assert.equal(r.mode,'clarification');assert.equal(r.sources.length,0);assert.equal(scopeData(fixture(),rep).customers.length,3);});
test('ambiguous first name asks for full name',()=>{const r=resolveEntity('عثمان',[{id:'1',name:'عثمان أحمد'},{id:'2',name:'عثمان علي'}]);assert.ok(r.question);assert.equal(r.item,undefined);});
test('one-letter typo resolves only when unambiguous',()=>{assert.equal(resolveEntity('عثماان',fixture().reps).item.id,'osman');});
test('conversation carries representative, due filter and sort',()=>{const d=fixture();const first=fallbackPlan('أعلى ديون عثمان',{},d);const second=fallbackPlan('المستحق منها فقط',first,d);const third=fallbackPlan('رتبهم من الأقل',second,d);assert.equal(third.rep,'عثمان أحمد');assert.equal(third.dueOnly,true);assert.equal(third.sort,'asc');assert.equal(executePlan(third,d,admin).metrics.total,200);});
test('unknown named scope never falls back to overall total',()=>{const p=fallbackPlan('أعلى ديون خالد',{},fixture());assert.ok(p.clarification);});
test('collections period uses dates and keeps representative scope',()=>{const p=fallbackPlan('تحصيل عثمان الشهر الماضي',{},fixture(),'2026-09-14');assert.equal(p.from,'2026-08-01');assert.equal(p.to,'2026-08-31');const r=executePlan(p,fixture(),admin);assert.ok(r.answer.includes('٥٠٠'));assert.ok(!r.answer.includes('٨٠٠'));});
test('historical balances cannot be fabricated from current balances',()=>{assert.equal(executePlan({action:'debts',from:'2026-08-01',to:'2026-08-31'},fixture(),admin).mode,'clarification');});
test('invalid and reversed dates are rejected',()=>{assert.ok(normalizePlan({from:'2026-02-30'}).clarification);assert.ok(normalizePlan({from:'2026-09-15',to:'2026-09-01'}).clarification);});
test('Saudi calendar changes at UTC 21:00',()=>{assert.equal(saudiDate('2026-09-14T21:30:00Z'),'2026-09-15');});
test('Arabic and comma-formatted amounts retain decimal precision',()=>{assert.equal(number('١٬٢٣٤٫٥٠'),1234.5);assert.equal(number('1,234.50'),1234.5);assert.equal(number(''),null);assert.equal(number('abc'),null);});
test('quote draft changes quantity and colors without changing original',()=>{const d=fixture(),r=executePlan({action:'quote_draft',customer:'زهرة الروضة',changes:{total_kg:1000,print_colors:8}},d,admin);assert.equal(r.draft.total_kg,1000);assert.equal(r.draft.print_colors,8);assert.equal(r.draft.public_token,undefined);assert.equal(r.draft.customer_signature,undefined);assert.equal(r.draft.id,undefined);assert.equal(d.quotes[0].total_kg,500);});
test('invalid draft changes do not produce a draft',()=>{const r=executePlan({action:'quote_draft',customer:'زهرة الروضة',changes:{print_colors:99}},fixture(),admin);assert.equal(r.mode,'clarification');assert.equal(r.draft,undefined);});
test('multiple items require clarification before bulk quantity changes',()=>{const d=fixture();d.quotes[0].items=[{total_kg:2},{total_kg:3}];assert.equal(executePlan({action:'quote_draft',customer:'زهرة الروضة',changes:{total_kg:1000}},d,admin).mode,'clarification');});
test('production tracking follows quote to sales order to manufacturing',()=>{const d=fixture();d.orders=[{id:'o1',source_quote_id:'q1',customer_id:'a',rep_id:'osman',status:'بانتظار اعتماد المدير'}];d.manufacturing=[{id:'m1',source_order_id:'o1',source_quote_id:'q1',customer_id:'a',rep_id:'osman',status:'in_progress',operations:[{work_center:'printing',status:'blocked'}]}];const r=executePlan({action:'order_tracking',reference:'Q-100'},d,admin);assert.ok(r.answer.includes('o1'));assert.ok(r.answer.includes('m1'));assert.ok(r.answer.includes('متعطل'));});
test('missing deadlines are disclosed in manager priorities',()=>{const d=fixture();d.manufacturing=[{id:'m1',rep_id:'osman',status:'in_progress'}];const r=executePlan({action:'attention'},d,admin);assert.ok(r.answer.includes('بدون موعد مسجل'));});
test('malicious unsupported action is never executed',()=>{const r=executePlan({action:'delete_customers',sql:'DELETE FROM jms_customers'},fixture(),admin);assert.equal(r.mode,'clarification');assert.equal(r.draft,undefined);});
